# Generated by tools/generate_bindings.py. Do not edit.
class_name Box3D
extends RefCounted

var raw: Box3DRaw

func _init(p_raw: Box3DRaw = null) -> void:
	raw = p_raw if p_raw != null else Box3DRaw.new()

func b3AABB_Area(arg0):
	return raw.call_box3d(&"b3AABB_Area", [arg0])

func b3AABB_Center(arg0):
	return raw.call_box3d(&"b3AABB_Center", [arg0])

func b3AABB_Contains(arg0, arg1):
	return raw.call_box3d(&"b3AABB_Contains", [arg0, arg1])

func b3AABB_Extents(arg0):
	return raw.call_box3d(&"b3AABB_Extents", [arg0])

func b3AABB_Inflate(arg0, arg1):
	return raw.call_box3d(&"b3AABB_Inflate", [arg0, arg1])

func b3AABB_Overlaps(arg0, arg1):
	return raw.call_box3d(&"b3AABB_Overlaps", [arg0, arg1])

func b3AABB_Transform(arg0, arg1):
	return raw.call_box3d(&"b3AABB_Transform", [arg0, arg1])

func b3AABB_Union(arg0, arg1):
	return raw.call_box3d(&"b3AABB_Union", [arg0, arg1])

func b3Abs(arg0):
	return raw.call_box3d(&"b3Abs", [arg0])

func b3AbsFloat(arg0):
	return raw.call_box3d(&"b3AbsFloat", [arg0])

func b3AbsMatrix3(arg0):
	return raw.call_box3d(&"b3AbsMatrix3", [arg0])

func b3Add(arg0, arg1):
	return raw.call_box3d(&"b3Add", [arg0, arg1])

func b3AddMM(arg0, arg1):
	return raw.call_box3d(&"b3AddMM", [arg0, arg1])

func b3Atan2(arg0, arg1):
	return raw.call_box3d(&"b3Atan2", [arg0, arg1])

func b3Blend2(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3Blend2", [arg0, arg1, arg2, arg3])

func b3Body_ApplyAngularImpulse(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_ApplyAngularImpulse", [arg0, arg1, arg2])

func b3Body_ApplyForce(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3Body_ApplyForce", [arg0, arg1, arg2, arg3])

func b3Body_ApplyForceToCenter(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_ApplyForceToCenter", [arg0, arg1, arg2])

func b3Body_ApplyLinearImpulse(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3Body_ApplyLinearImpulse", [arg0, arg1, arg2, arg3])

func b3Body_ApplyLinearImpulseToCenter(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_ApplyLinearImpulseToCenter", [arg0, arg1, arg2])

func b3Body_ApplyMassFromShapes(arg0):
	return raw.call_box3d(&"b3Body_ApplyMassFromShapes", [arg0])

func b3Body_ApplyTorque(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_ApplyTorque", [arg0, arg1, arg2])

func b3Body_CastRay(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3Body_CastRay", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3Body_CastShape(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7):
	return raw.call_box3d(&"b3Body_CastShape", [arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7])

func b3Body_CollideMover(arg0, arg1, arg2, arg3, arg4, arg5, arg6):
	return raw.call_box3d(&"b3Body_CollideMover", [arg0, arg1, arg2, arg3, arg4, arg5, arg6])

func b3Body_ComputeAABB(arg0):
	return raw.call_box3d(&"b3Body_ComputeAABB", [arg0])

func b3Body_Disable(arg0):
	return raw.call_box3d(&"b3Body_Disable", [arg0])

func b3Body_Enable(arg0):
	return raw.call_box3d(&"b3Body_Enable", [arg0])

func b3Body_EnableContactRecycling(arg0, arg1):
	return raw.call_box3d(&"b3Body_EnableContactRecycling", [arg0, arg1])

func b3Body_EnableHitEvents(arg0, arg1):
	return raw.call_box3d(&"b3Body_EnableHitEvents", [arg0, arg1])

func b3Body_EnableSleep(arg0, arg1):
	return raw.call_box3d(&"b3Body_EnableSleep", [arg0, arg1])

func b3Body_GetAngularDamping(arg0):
	return raw.call_box3d(&"b3Body_GetAngularDamping", [arg0])

func b3Body_GetAngularVelocity(arg0):
	return raw.call_box3d(&"b3Body_GetAngularVelocity", [arg0])

func b3Body_GetClosestPoint(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_GetClosestPoint", [arg0, arg1, arg2])

func b3Body_GetContactCapacity(arg0):
	return raw.call_box3d(&"b3Body_GetContactCapacity", [arg0])

func b3Body_GetContactData(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_GetContactData", [arg0, arg1, arg2])

func b3Body_GetGravityScale(arg0):
	return raw.call_box3d(&"b3Body_GetGravityScale", [arg0])

func b3Body_GetInverseMass(arg0):
	return raw.call_box3d(&"b3Body_GetInverseMass", [arg0])

func b3Body_GetJointCount(arg0):
	return raw.call_box3d(&"b3Body_GetJointCount", [arg0])

func b3Body_GetJoints(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_GetJoints", [arg0, arg1, arg2])

func b3Body_GetLinearDamping(arg0):
	return raw.call_box3d(&"b3Body_GetLinearDamping", [arg0])

func b3Body_GetLinearVelocity(arg0):
	return raw.call_box3d(&"b3Body_GetLinearVelocity", [arg0])

func b3Body_GetLocalCenter(arg0):
	return raw.call_box3d(&"b3Body_GetLocalCenter", [arg0])

func b3Body_GetLocalPoint(arg0, arg1):
	return raw.call_box3d(&"b3Body_GetLocalPoint", [arg0, arg1])

func b3Body_GetLocalPointVelocity(arg0, arg1):
	return raw.call_box3d(&"b3Body_GetLocalPointVelocity", [arg0, arg1])

func b3Body_GetLocalRotationalInertia(arg0):
	return raw.call_box3d(&"b3Body_GetLocalRotationalInertia", [arg0])

func b3Body_GetLocalVector(arg0, arg1):
	return raw.call_box3d(&"b3Body_GetLocalVector", [arg0, arg1])

func b3Body_GetMass(arg0):
	return raw.call_box3d(&"b3Body_GetMass", [arg0])

func b3Body_GetMassData(arg0):
	return raw.call_box3d(&"b3Body_GetMassData", [arg0])

func b3Body_GetMotionLocks(arg0):
	return raw.call_box3d(&"b3Body_GetMotionLocks", [arg0])

func b3Body_GetName(arg0):
	return raw.call_box3d(&"b3Body_GetName", [arg0])

func b3Body_GetPosition(arg0):
	return raw.call_box3d(&"b3Body_GetPosition", [arg0])

func b3Body_GetRotation(arg0):
	return raw.call_box3d(&"b3Body_GetRotation", [arg0])

func b3Body_GetShapeCount(arg0):
	return raw.call_box3d(&"b3Body_GetShapeCount", [arg0])

func b3Body_GetShapes(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_GetShapes", [arg0, arg1, arg2])

func b3Body_GetSleepThreshold(arg0):
	return raw.call_box3d(&"b3Body_GetSleepThreshold", [arg0])

func b3Body_GetTransform(arg0):
	return raw.call_box3d(&"b3Body_GetTransform", [arg0])

func b3Body_GetType(arg0):
	return raw.call_box3d(&"b3Body_GetType", [arg0])

func b3Body_GetUserData(arg0):
	return raw.call_box3d(&"b3Body_GetUserData", [arg0])

func b3Body_GetWorld(arg0):
	return raw.call_box3d(&"b3Body_GetWorld", [arg0])

func b3Body_GetWorldCenter(arg0):
	return raw.call_box3d(&"b3Body_GetWorldCenter", [arg0])

func b3Body_GetWorldInverseRotationalInertia(arg0):
	return raw.call_box3d(&"b3Body_GetWorldInverseRotationalInertia", [arg0])

func b3Body_GetWorldPoint(arg0, arg1):
	return raw.call_box3d(&"b3Body_GetWorldPoint", [arg0, arg1])

func b3Body_GetWorldPointVelocity(arg0, arg1):
	return raw.call_box3d(&"b3Body_GetWorldPointVelocity", [arg0, arg1])

func b3Body_GetWorldVector(arg0, arg1):
	return raw.call_box3d(&"b3Body_GetWorldVector", [arg0, arg1])

func b3Body_IsAwake(arg0):
	return raw.call_box3d(&"b3Body_IsAwake", [arg0])

func b3Body_IsBullet(arg0):
	return raw.call_box3d(&"b3Body_IsBullet", [arg0])

func b3Body_IsContactRecyclingEnabled(arg0):
	return raw.call_box3d(&"b3Body_IsContactRecyclingEnabled", [arg0])

func b3Body_IsEnabled(arg0):
	return raw.call_box3d(&"b3Body_IsEnabled", [arg0])

func b3Body_IsSleepEnabled(arg0):
	return raw.call_box3d(&"b3Body_IsSleepEnabled", [arg0])

func b3Body_IsValid(arg0):
	return raw.call_box3d(&"b3Body_IsValid", [arg0])

func b3Body_OverlapShape(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3Body_OverlapShape", [arg0, arg1, arg2, arg3, arg4])

func b3Body_SetAngularDamping(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetAngularDamping", [arg0, arg1])

func b3Body_SetAngularVelocity(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetAngularVelocity", [arg0, arg1])

func b3Body_SetAwake(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetAwake", [arg0, arg1])

func b3Body_SetBullet(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetBullet", [arg0, arg1])

func b3Body_SetGravityScale(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetGravityScale", [arg0, arg1])

func b3Body_SetLinearDamping(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetLinearDamping", [arg0, arg1])

func b3Body_SetLinearVelocity(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetLinearVelocity", [arg0, arg1])

func b3Body_SetMassData(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetMassData", [arg0, arg1])

func b3Body_SetMotionLocks(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetMotionLocks", [arg0, arg1])

func b3Body_SetName(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetName", [arg0, arg1])

func b3Body_SetSleepThreshold(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetSleepThreshold", [arg0, arg1])

func b3Body_SetTargetTransform(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3Body_SetTargetTransform", [arg0, arg1, arg2, arg3])

func b3Body_SetTransform(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Body_SetTransform", [arg0, arg1, arg2])

func b3Body_SetType(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetType", [arg0, arg1])

func b3Body_SetUserData(arg0, arg1):
	return raw.call_box3d(&"b3Body_SetUserData", [arg0, arg1])

func b3Clamp(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Clamp", [arg0, arg1, arg2])

func b3ClampFloat(arg0, arg1, arg2):
	return raw.call_box3d(&"b3ClampFloat", [arg0, arg1, arg2])

func b3ClampInt(arg0, arg1, arg2):
	return raw.call_box3d(&"b3ClampInt", [arg0, arg1, arg2])

func b3ClipVector(arg0, arg1, arg2):
	return raw.call_box3d(&"b3ClipVector", [arg0, arg1, arg2])

func b3CloneAndTransformHull(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CloneAndTransformHull", [arg0, arg1, arg2])

func b3CloneHull(arg0):
	return raw.call_box3d(&"b3CloneHull", [arg0])

func b3ClosestPointToAABB(arg0, arg1):
	return raw.call_box3d(&"b3ClosestPointToAABB", [arg0, arg1])

func b3CollideCapsuleAndSphere(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3CollideCapsuleAndSphere", [arg0, arg1, arg2, arg3, arg4])

func b3CollideCapsuleAndTriangle(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3CollideCapsuleAndTriangle", [arg0, arg1, arg2, arg3, arg4])

func b3CollideCapsules(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3CollideCapsules", [arg0, arg1, arg2, arg3, arg4])

func b3CollideHullAndCapsule(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3CollideHullAndCapsule", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3CollideHullAndSphere(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3CollideHullAndSphere", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3CollideHullAndTriangle(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7):
	return raw.call_box3d(&"b3CollideHullAndTriangle", [arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7])

func b3CollideHulls(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3CollideHulls", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3CollideSphereAndTriangle(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CollideSphereAndTriangle", [arg0, arg1, arg2, arg3])

func b3CollideSpheres(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3CollideSpheres", [arg0, arg1, arg2, arg3, arg4])

func b3ComputeCapsuleAABB(arg0, arg1):
	return raw.call_box3d(&"b3ComputeCapsuleAABB", [arg0, arg1])

func b3ComputeCapsuleMass(arg0, arg1):
	return raw.call_box3d(&"b3ComputeCapsuleMass", [arg0, arg1])

func b3ComputeCompoundAABB(arg0, arg1):
	return raw.call_box3d(&"b3ComputeCompoundAABB", [arg0, arg1])

func b3ComputeCosSin(arg0):
	return raw.call_box3d(&"b3ComputeCosSin", [arg0])

func b3ComputeHeightFieldAABB(arg0, arg1):
	return raw.call_box3d(&"b3ComputeHeightFieldAABB", [arg0, arg1])

func b3ComputeHullAABB(arg0, arg1):
	return raw.call_box3d(&"b3ComputeHullAABB", [arg0, arg1])

func b3ComputeHullMass(arg0, arg1):
	return raw.call_box3d(&"b3ComputeHullMass", [arg0, arg1])

func b3ComputeMeshAABB(arg0, arg1, arg2):
	return raw.call_box3d(&"b3ComputeMeshAABB", [arg0, arg1, arg2])

func b3ComputeQuatBetweenUnitVectors(arg0, arg1):
	return raw.call_box3d(&"b3ComputeQuatBetweenUnitVectors", [arg0, arg1])

func b3ComputeSphereAABB(arg0, arg1):
	return raw.call_box3d(&"b3ComputeSphereAABB", [arg0, arg1])

func b3ComputeSphereMass(arg0, arg1):
	return raw.call_box3d(&"b3ComputeSphereMass", [arg0, arg1])

func b3Conjugate(arg0):
	return raw.call_box3d(&"b3Conjugate", [arg0])

func b3Contact_GetData(arg0):
	return raw.call_box3d(&"b3Contact_GetData", [arg0])

func b3Contact_IsValid(arg0):
	return raw.call_box3d(&"b3Contact_IsValid", [arg0])

func b3ConvertBytesToCompound(arg0, arg1):
	return raw.call_box3d(&"b3ConvertBytesToCompound", [arg0, arg1])

func b3ConvertCompoundToBytes(arg0):
	return raw.call_box3d(&"b3ConvertCompoundToBytes", [arg0])

func b3Cos(arg0):
	return raw.call_box3d(&"b3Cos", [arg0])

func b3CreateBody(arg0, arg1):
	return raw.call_box3d(&"b3CreateBody", [arg0, arg1])

func b3CreateBoxMesh(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateBoxMesh", [arg0, arg1, arg2])

func b3CreateCapsuleShape(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateCapsuleShape", [arg0, arg1, arg2])

func b3CreateCompound(arg0):
	return raw.call_box3d(&"b3CreateCompound", [arg0])

func b3CreateCompoundShape(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateCompoundShape", [arg0, arg1, arg2])

func b3CreateCone(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CreateCone", [arg0, arg1, arg2, arg3])

func b3CreateCylinder(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CreateCylinder", [arg0, arg1, arg2, arg3])

func b3CreateDistanceJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateDistanceJoint", [arg0, arg1])

func b3CreateFilterJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateFilterJoint", [arg0, arg1])

func b3CreateGrid(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CreateGrid", [arg0, arg1, arg2, arg3])

func b3CreateGridMesh(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3CreateGridMesh", [arg0, arg1, arg2, arg3, arg4])

func b3CreateHeightField(arg0):
	return raw.call_box3d(&"b3CreateHeightField", [arg0])

func b3CreateHeightFieldShape(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateHeightFieldShape", [arg0, arg1, arg2])

func b3CreateHollowBoxMesh(arg0, arg1):
	return raw.call_box3d(&"b3CreateHollowBoxMesh", [arg0, arg1])

func b3CreateHull(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateHull", [arg0, arg1, arg2])

func b3CreateHullShape(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateHullShape", [arg0, arg1, arg2])

func b3CreateMesh(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateMesh", [arg0, arg1, arg2])

func b3CreateMeshShape(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CreateMeshShape", [arg0, arg1, arg2, arg3])

func b3CreateMotorJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateMotorJoint", [arg0, arg1])

func b3CreateParallelJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateParallelJoint", [arg0, arg1])

func b3CreatePlatformMesh(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CreatePlatformMesh", [arg0, arg1, arg2, arg3])

func b3CreatePrismaticJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreatePrismaticJoint", [arg0, arg1])

func b3CreateRecording(arg0):
	return raw.call_box3d(&"b3CreateRecording", [arg0])

func b3CreateRevoluteJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateRevoluteJoint", [arg0, arg1])

func b3CreateRock(arg0):
	return raw.call_box3d(&"b3CreateRock", [arg0])

func b3CreateSphereShape(arg0, arg1, arg2):
	return raw.call_box3d(&"b3CreateSphereShape", [arg0, arg1, arg2])

func b3CreateSphericalJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateSphericalJoint", [arg0, arg1])

func b3CreateTorusMesh(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3CreateTorusMesh", [arg0, arg1, arg2, arg3])

func b3CreateTransformedHullShape(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3CreateTransformedHullShape", [arg0, arg1, arg2, arg3, arg4])

func b3CreateWave(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3CreateWave", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3CreateWaveMesh(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3CreateWaveMesh", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3CreateWeldJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateWeldJoint", [arg0, arg1])

func b3CreateWheelJoint(arg0, arg1):
	return raw.call_box3d(&"b3CreateWheelJoint", [arg0, arg1])

func b3CreateWorld(arg0):
	return raw.call_box3d(&"b3CreateWorld", [arg0])

func b3Cross(arg0, arg1):
	return raw.call_box3d(&"b3Cross", [arg0, arg1])

func b3DefaultBodyDef():
	return raw.call_box3d(&"b3DefaultBodyDef", [])

func b3DefaultDebugDraw():
	return raw.call_box3d(&"b3DefaultDebugDraw", [])

func b3DefaultDistanceJointDef():
	return raw.call_box3d(&"b3DefaultDistanceJointDef", [])

func b3DefaultExplosionDef():
	return raw.call_box3d(&"b3DefaultExplosionDef", [])

func b3DefaultFilter():
	return raw.call_box3d(&"b3DefaultFilter", [])

func b3DefaultFilterJointDef():
	return raw.call_box3d(&"b3DefaultFilterJointDef", [])

func b3DefaultMotorJointDef():
	return raw.call_box3d(&"b3DefaultMotorJointDef", [])

func b3DefaultParallelJointDef():
	return raw.call_box3d(&"b3DefaultParallelJointDef", [])

func b3DefaultPrismaticJointDef():
	return raw.call_box3d(&"b3DefaultPrismaticJointDef", [])

func b3DefaultQueryFilter():
	return raw.call_box3d(&"b3DefaultQueryFilter", [])

func b3DefaultRevoluteJointDef():
	return raw.call_box3d(&"b3DefaultRevoluteJointDef", [])

func b3DefaultShapeDef():
	return raw.call_box3d(&"b3DefaultShapeDef", [])

func b3DefaultSphericalJointDef():
	return raw.call_box3d(&"b3DefaultSphericalJointDef", [])

func b3DefaultSurfaceMaterial():
	return raw.call_box3d(&"b3DefaultSurfaceMaterial", [])

func b3DefaultWeldJointDef():
	return raw.call_box3d(&"b3DefaultWeldJointDef", [])

func b3DefaultWheelJointDef():
	return raw.call_box3d(&"b3DefaultWheelJointDef", [])

func b3DefaultWorldDef():
	return raw.call_box3d(&"b3DefaultWorldDef", [])

func b3DestroyBody(arg0):
	return raw.call_box3d(&"b3DestroyBody", [arg0])

func b3DestroyCompound(arg0):
	return raw.call_box3d(&"b3DestroyCompound", [arg0])

func b3DestroyHeightField(arg0):
	return raw.call_box3d(&"b3DestroyHeightField", [arg0])

func b3DestroyHull(arg0):
	return raw.call_box3d(&"b3DestroyHull", [arg0])

func b3DestroyJoint(arg0, arg1):
	return raw.call_box3d(&"b3DestroyJoint", [arg0, arg1])

func b3DestroyMesh(arg0):
	return raw.call_box3d(&"b3DestroyMesh", [arg0])

func b3DestroyRecording(arg0):
	return raw.call_box3d(&"b3DestroyRecording", [arg0])

func b3DestroyShape(arg0, arg1):
	return raw.call_box3d(&"b3DestroyShape", [arg0, arg1])

func b3DestroyWorld(arg0):
	return raw.call_box3d(&"b3DestroyWorld", [arg0])

func b3Det(arg0):
	return raw.call_box3d(&"b3Det", [arg0])

func b3Distance(arg0, arg1):
	return raw.call_box3d(&"b3Distance", [arg0, arg1])

func b3DistanceJoint_EnableLimit(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_EnableLimit", [arg0, arg1])

func b3DistanceJoint_EnableMotor(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_EnableMotor", [arg0, arg1])

func b3DistanceJoint_EnableSpring(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_EnableSpring", [arg0, arg1])

func b3DistanceJoint_GetCurrentLength(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetCurrentLength", [arg0])

func b3DistanceJoint_GetLength(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetLength", [arg0])

func b3DistanceJoint_GetMaxLength(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetMaxLength", [arg0])

func b3DistanceJoint_GetMaxMotorForce(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetMaxMotorForce", [arg0])

func b3DistanceJoint_GetMinLength(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetMinLength", [arg0])

func b3DistanceJoint_GetMotorForce(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetMotorForce", [arg0])

func b3DistanceJoint_GetMotorSpeed(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetMotorSpeed", [arg0])

func b3DistanceJoint_GetSpringDampingRatio(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetSpringDampingRatio", [arg0])

func b3DistanceJoint_GetSpringForceRange(arg0, arg1, arg2):
	return raw.call_box3d(&"b3DistanceJoint_GetSpringForceRange", [arg0, arg1, arg2])

func b3DistanceJoint_GetSpringHertz(arg0):
	return raw.call_box3d(&"b3DistanceJoint_GetSpringHertz", [arg0])

func b3DistanceJoint_IsLimitEnabled(arg0):
	return raw.call_box3d(&"b3DistanceJoint_IsLimitEnabled", [arg0])

func b3DistanceJoint_IsMotorEnabled(arg0):
	return raw.call_box3d(&"b3DistanceJoint_IsMotorEnabled", [arg0])

func b3DistanceJoint_IsSpringEnabled(arg0):
	return raw.call_box3d(&"b3DistanceJoint_IsSpringEnabled", [arg0])

func b3DistanceJoint_SetLength(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_SetLength", [arg0, arg1])

func b3DistanceJoint_SetLengthRange(arg0, arg1, arg2):
	return raw.call_box3d(&"b3DistanceJoint_SetLengthRange", [arg0, arg1, arg2])

func b3DistanceJoint_SetMaxMotorForce(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_SetMaxMotorForce", [arg0, arg1])

func b3DistanceJoint_SetMotorSpeed(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_SetMotorSpeed", [arg0, arg1])

func b3DistanceJoint_SetSpringDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_SetSpringDampingRatio", [arg0, arg1])

func b3DistanceJoint_SetSpringForceRange(arg0, arg1, arg2):
	return raw.call_box3d(&"b3DistanceJoint_SetSpringForceRange", [arg0, arg1, arg2])

func b3DistanceJoint_SetSpringHertz(arg0, arg1):
	return raw.call_box3d(&"b3DistanceJoint_SetSpringHertz", [arg0, arg1])

func b3DistanceSquared(arg0, arg1):
	return raw.call_box3d(&"b3DistanceSquared", [arg0, arg1])

func b3Dot(arg0, arg1):
	return raw.call_box3d(&"b3Dot", [arg0, arg1])

func b3DotQuat(arg0, arg1):
	return raw.call_box3d(&"b3DotQuat", [arg0, arg1])

func b3DumpHeightData(arg0, arg1):
	return raw.call_box3d(&"b3DumpHeightData", [arg0, arg1])

func b3DynamicTree_BoxCast(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3DynamicTree_BoxCast", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3DynamicTree_Create(arg0):
	return raw.call_box3d(&"b3DynamicTree_Create", [arg0])

func b3DynamicTree_CreateProxy(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3DynamicTree_CreateProxy", [arg0, arg1, arg2, arg3])

func b3DynamicTree_Destroy(arg0):
	return raw.call_box3d(&"b3DynamicTree_Destroy", [arg0])

func b3DynamicTree_DestroyProxy(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_DestroyProxy", [arg0, arg1])

func b3DynamicTree_EnlargeProxy(arg0, arg1, arg2):
	return raw.call_box3d(&"b3DynamicTree_EnlargeProxy", [arg0, arg1, arg2])

func b3DynamicTree_GetAABB(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_GetAABB", [arg0, arg1])

func b3DynamicTree_GetAreaRatio(arg0):
	return raw.call_box3d(&"b3DynamicTree_GetAreaRatio", [arg0])

func b3DynamicTree_GetByteCount(arg0):
	return raw.call_box3d(&"b3DynamicTree_GetByteCount", [arg0])

func b3DynamicTree_GetCategoryBits(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_GetCategoryBits", [arg0, arg1])

func b3DynamicTree_GetHeight(arg0):
	return raw.call_box3d(&"b3DynamicTree_GetHeight", [arg0])

func b3DynamicTree_GetProxyCount(arg0):
	return raw.call_box3d(&"b3DynamicTree_GetProxyCount", [arg0])

func b3DynamicTree_GetRootBounds(arg0):
	return raw.call_box3d(&"b3DynamicTree_GetRootBounds", [arg0])

func b3DynamicTree_GetUserData(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_GetUserData", [arg0, arg1])

func b3DynamicTree_Load(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_Load", [arg0, arg1])

func b3DynamicTree_MoveProxy(arg0, arg1, arg2):
	return raw.call_box3d(&"b3DynamicTree_MoveProxy", [arg0, arg1, arg2])

func b3DynamicTree_Query(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3DynamicTree_Query", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3DynamicTree_QueryClosest(arg0, arg1, arg2, arg3, arg4, arg5, arg6):
	return raw.call_box3d(&"b3DynamicTree_QueryClosest", [arg0, arg1, arg2, arg3, arg4, arg5, arg6])

func b3DynamicTree_RayCast(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3DynamicTree_RayCast", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3DynamicTree_Rebuild(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_Rebuild", [arg0, arg1])

func b3DynamicTree_Save(arg0, arg1):
	return raw.call_box3d(&"b3DynamicTree_Save", [arg0, arg1])

func b3DynamicTree_SetCategoryBits(arg0, arg1, arg2):
	return raw.call_box3d(&"b3DynamicTree_SetCategoryBits", [arg0, arg1, arg2])

func b3DynamicTree_Validate(arg0):
	return raw.call_box3d(&"b3DynamicTree_Validate", [arg0])

func b3DynamicTree_ValidateNoEnlarged(arg0):
	return raw.call_box3d(&"b3DynamicTree_ValidateNoEnlarged", [arg0])

func b3GetAxisAngle(arg0, arg1):
	return raw.call_box3d(&"b3GetAxisAngle", [arg0, arg1])

func b3GetByteCount():
	return raw.call_box3d(&"b3GetByteCount", [])

func b3GetCompoundCapsule(arg0, arg1):
	return raw.call_box3d(&"b3GetCompoundCapsule", [arg0, arg1])

func b3GetCompoundChild(arg0, arg1):
	return raw.call_box3d(&"b3GetCompoundChild", [arg0, arg1])

func b3GetCompoundHull(arg0, arg1):
	return raw.call_box3d(&"b3GetCompoundHull", [arg0, arg1])

func b3GetCompoundMaterials(arg0):
	return raw.call_box3d(&"b3GetCompoundMaterials", [arg0])

func b3GetCompoundMesh(arg0, arg1):
	return raw.call_box3d(&"b3GetCompoundMesh", [arg0, arg1])

func b3GetCompoundSphere(arg0, arg1):
	return raw.call_box3d(&"b3GetCompoundSphere", [arg0, arg1])

func b3GetGraphColor(arg0):
	return raw.call_box3d(&"b3GetGraphColor", [arg0])

func b3GetHeight(arg0):
	return raw.call_box3d(&"b3GetHeight", [arg0])

func b3GetHeightFieldCompressedHeights(arg0):
	return raw.call_box3d(&"b3GetHeightFieldCompressedHeights", [arg0])

func b3GetHeightFieldFlags(arg0):
	return raw.call_box3d(&"b3GetHeightFieldFlags", [arg0])

func b3GetHeightFieldMaterialIndices(arg0):
	return raw.call_box3d(&"b3GetHeightFieldMaterialIndices", [arg0])

func b3GetHullEdges(arg0):
	return raw.call_box3d(&"b3GetHullEdges", [arg0])

func b3GetHullFaces(arg0):
	return raw.call_box3d(&"b3GetHullFaces", [arg0])

func b3GetHullPlanes(arg0):
	return raw.call_box3d(&"b3GetHullPlanes", [arg0])

func b3GetHullPoints(arg0):
	return raw.call_box3d(&"b3GetHullPoints", [arg0])

func b3GetHullVertices(arg0):
	return raw.call_box3d(&"b3GetHullVertices", [arg0])

func b3GetLengthAndNormalize(arg0, arg1):
	return raw.call_box3d(&"b3GetLengthAndNormalize", [arg0, arg1])

func b3GetLengthUnitsPerMeter():
	return raw.call_box3d(&"b3GetLengthUnitsPerMeter", [])

func b3GetMaxWorldCount():
	return raw.call_box3d(&"b3GetMaxWorldCount", [])

func b3GetMeshFlags(arg0):
	return raw.call_box3d(&"b3GetMeshFlags", [arg0])

func b3GetMeshMaterialIndices(arg0):
	return raw.call_box3d(&"b3GetMeshMaterialIndices", [arg0])

func b3GetMeshNodes(arg0):
	return raw.call_box3d(&"b3GetMeshNodes", [arg0])

func b3GetMeshTriangles(arg0):
	return raw.call_box3d(&"b3GetMeshTriangles", [arg0])

func b3GetMeshVertices(arg0):
	return raw.call_box3d(&"b3GetMeshVertices", [arg0])

func b3GetMilliseconds(arg0):
	return raw.call_box3d(&"b3GetMilliseconds", [arg0])

func b3GetMillisecondsAndReset(arg0):
	return raw.call_box3d(&"b3GetMillisecondsAndReset", [arg0])

func b3GetQuatAngle(arg0):
	return raw.call_box3d(&"b3GetQuatAngle", [arg0])

func b3GetStallThreshold():
	return raw.call_box3d(&"b3GetStallThreshold", [])

func b3GetSweepTransform(arg0, arg1):
	return raw.call_box3d(&"b3GetSweepTransform", [arg0, arg1])

func b3GetSwingAngle(arg0):
	return raw.call_box3d(&"b3GetSwingAngle", [arg0])

func b3GetTicks():
	return raw.call_box3d(&"b3GetTicks", [])

func b3GetTwistAngle(arg0):
	return raw.call_box3d(&"b3GetTwistAngle", [arg0])

func b3GetVersion():
	return raw.call_box3d(&"b3GetVersion", [])

func b3GetWorldCount():
	return raw.call_box3d(&"b3GetWorldCount", [])

func b3Hash(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Hash", [arg0, arg1, arg2])

func b3InvMulQuat(arg0, arg1):
	return raw.call_box3d(&"b3InvMulQuat", [arg0, arg1])

func b3InvMulTransforms(arg0, arg1):
	return raw.call_box3d(&"b3InvMulTransforms", [arg0, arg1])

func b3InvMulWorldTransforms(arg0, arg1):
	return raw.call_box3d(&"b3InvMulWorldTransforms", [arg0, arg1])

func b3InvRotateVector(arg0, arg1):
	return raw.call_box3d(&"b3InvRotateVector", [arg0, arg1])

func b3InvTransformPoint(arg0, arg1):
	return raw.call_box3d(&"b3InvTransformPoint", [arg0, arg1])

func b3InvTransformWorldPoint(arg0, arg1):
	return raw.call_box3d(&"b3InvTransformWorldPoint", [arg0, arg1])

func b3InvertMatrix(arg0):
	return raw.call_box3d(&"b3InvertMatrix", [arg0])

func b3InvertT(arg0):
	return raw.call_box3d(&"b3InvertT", [arg0])

func b3InvertTransform(arg0):
	return raw.call_box3d(&"b3InvertTransform", [arg0])

func b3IsBoundedAABB(arg0):
	return raw.call_box3d(&"b3IsBoundedAABB", [arg0])

func b3IsDoublePrecision():
	return raw.call_box3d(&"b3IsDoublePrecision", [])

func b3IsNormalized(arg0):
	return raw.call_box3d(&"b3IsNormalized", [arg0])

func b3IsNormalizedQuat(arg0):
	return raw.call_box3d(&"b3IsNormalizedQuat", [arg0])

func b3IsSaneAABB(arg0):
	return raw.call_box3d(&"b3IsSaneAABB", [arg0])

func b3IsValidAABB(arg0):
	return raw.call_box3d(&"b3IsValidAABB", [arg0])

func b3IsValidFloat(arg0):
	return raw.call_box3d(&"b3IsValidFloat", [arg0])

func b3IsValidMatrix3(arg0):
	return raw.call_box3d(&"b3IsValidMatrix3", [arg0])

func b3IsValidPlane(arg0):
	return raw.call_box3d(&"b3IsValidPlane", [arg0])

func b3IsValidPosition(arg0):
	return raw.call_box3d(&"b3IsValidPosition", [arg0])

func b3IsValidQuat(arg0):
	return raw.call_box3d(&"b3IsValidQuat", [arg0])

func b3IsValidRay(arg0):
	return raw.call_box3d(&"b3IsValidRay", [arg0])

func b3IsValidTransform(arg0):
	return raw.call_box3d(&"b3IsValidTransform", [arg0])

func b3IsValidVec3(arg0):
	return raw.call_box3d(&"b3IsValidVec3", [arg0])

func b3IsValidWorldTransform(arg0):
	return raw.call_box3d(&"b3IsValidWorldTransform", [arg0])

func b3Joint_GetAngularSeparation(arg0):
	return raw.call_box3d(&"b3Joint_GetAngularSeparation", [arg0])

func b3Joint_GetBodyA(arg0):
	return raw.call_box3d(&"b3Joint_GetBodyA", [arg0])

func b3Joint_GetBodyB(arg0):
	return raw.call_box3d(&"b3Joint_GetBodyB", [arg0])

func b3Joint_GetCollideConnected(arg0):
	return raw.call_box3d(&"b3Joint_GetCollideConnected", [arg0])

func b3Joint_GetConstraintForce(arg0):
	return raw.call_box3d(&"b3Joint_GetConstraintForce", [arg0])

func b3Joint_GetConstraintTorque(arg0):
	return raw.call_box3d(&"b3Joint_GetConstraintTorque", [arg0])

func b3Joint_GetConstraintTuning(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Joint_GetConstraintTuning", [arg0, arg1, arg2])

func b3Joint_GetForceThreshold(arg0):
	return raw.call_box3d(&"b3Joint_GetForceThreshold", [arg0])

func b3Joint_GetLinearSeparation(arg0):
	return raw.call_box3d(&"b3Joint_GetLinearSeparation", [arg0])

func b3Joint_GetLocalFrameA(arg0):
	return raw.call_box3d(&"b3Joint_GetLocalFrameA", [arg0])

func b3Joint_GetLocalFrameB(arg0):
	return raw.call_box3d(&"b3Joint_GetLocalFrameB", [arg0])

func b3Joint_GetTorqueThreshold(arg0):
	return raw.call_box3d(&"b3Joint_GetTorqueThreshold", [arg0])

func b3Joint_GetType(arg0):
	return raw.call_box3d(&"b3Joint_GetType", [arg0])

func b3Joint_GetUserData(arg0):
	return raw.call_box3d(&"b3Joint_GetUserData", [arg0])

func b3Joint_GetWorld(arg0):
	return raw.call_box3d(&"b3Joint_GetWorld", [arg0])

func b3Joint_IsValid(arg0):
	return raw.call_box3d(&"b3Joint_IsValid", [arg0])

func b3Joint_SetCollideConnected(arg0, arg1):
	return raw.call_box3d(&"b3Joint_SetCollideConnected", [arg0, arg1])

func b3Joint_SetConstraintTuning(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Joint_SetConstraintTuning", [arg0, arg1, arg2])

func b3Joint_SetForceThreshold(arg0, arg1):
	return raw.call_box3d(&"b3Joint_SetForceThreshold", [arg0, arg1])

func b3Joint_SetLocalFrameA(arg0, arg1):
	return raw.call_box3d(&"b3Joint_SetLocalFrameA", [arg0, arg1])

func b3Joint_SetLocalFrameB(arg0, arg1):
	return raw.call_box3d(&"b3Joint_SetLocalFrameB", [arg0, arg1])

func b3Joint_SetTorqueThreshold(arg0, arg1):
	return raw.call_box3d(&"b3Joint_SetTorqueThreshold", [arg0, arg1])

func b3Joint_SetUserData(arg0, arg1):
	return raw.call_box3d(&"b3Joint_SetUserData", [arg0, arg1])

func b3Joint_WakeBodies(arg0):
	return raw.call_box3d(&"b3Joint_WakeBodies", [arg0])

func b3Length(arg0):
	return raw.call_box3d(&"b3Length", [arg0])

func b3LengthSquared(arg0):
	return raw.call_box3d(&"b3LengthSquared", [arg0])

func b3Lerp(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Lerp", [arg0, arg1, arg2])

func b3LerpFloat(arg0, arg1, arg2):
	return raw.call_box3d(&"b3LerpFloat", [arg0, arg1, arg2])

func b3LerpPosition(arg0, arg1, arg2):
	return raw.call_box3d(&"b3LerpPosition", [arg0, arg1, arg2])

func b3LineDistance(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3LineDistance", [arg0, arg1, arg2, arg3])

func b3LoadBodyId(arg0):
	return raw.call_box3d(&"b3LoadBodyId", [arg0])

func b3LoadContactId(arg0):
	return raw.call_box3d(&"b3LoadContactId", [arg0])

func b3LoadHeightField(arg0):
	return raw.call_box3d(&"b3LoadHeightField", [arg0])

func b3LoadJointId(arg0):
	return raw.call_box3d(&"b3LoadJointId", [arg0])

func b3LoadRecordingFromFile(arg0):
	return raw.call_box3d(&"b3LoadRecordingFromFile", [arg0])

func b3LoadShapeId(arg0):
	return raw.call_box3d(&"b3LoadShapeId", [arg0])

func b3LoadWorldId(arg0):
	return raw.call_box3d(&"b3LoadWorldId", [arg0])

func b3MakeAABB(arg0, arg1, arg2):
	return raw.call_box3d(&"b3MakeAABB", [arg0, arg1, arg2])

func b3MakeBoxHull(arg0, arg1, arg2):
	return raw.call_box3d(&"b3MakeBoxHull", [arg0, arg1, arg2])

func b3MakeCubeHull(arg0):
	return raw.call_box3d(&"b3MakeCubeHull", [arg0])

func b3MakeDebugColor(arg0, arg1):
	return raw.call_box3d(&"b3MakeDebugColor", [arg0, arg1])

func b3MakeMatrixFromQuat(arg0):
	return raw.call_box3d(&"b3MakeMatrixFromQuat", [arg0])

func b3MakeOffsetBoxHull(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3MakeOffsetBoxHull", [arg0, arg1, arg2, arg3])

func b3MakeQuatFromAxisAngle(arg0, arg1):
	return raw.call_box3d(&"b3MakeQuatFromAxisAngle", [arg0, arg1])

func b3MakeQuatFromMatrix(arg0):
	return raw.call_box3d(&"b3MakeQuatFromMatrix", [arg0])

func b3MakeScaledBoxHull(arg0, arg1, arg2):
	return raw.call_box3d(&"b3MakeScaledBoxHull", [arg0, arg1, arg2])

func b3MakeTransformedBoxHull(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3MakeTransformedBoxHull", [arg0, arg1, arg2, arg3])

func b3MakeWorldTransform(arg0):
	return raw.call_box3d(&"b3MakeWorldTransform", [arg0])

func b3Max(arg0, arg1):
	return raw.call_box3d(&"b3Max", [arg0, arg1])

func b3MaxFloat(arg0, arg1):
	return raw.call_box3d(&"b3MaxFloat", [arg0, arg1])

func b3MaxInt(arg0, arg1):
	return raw.call_box3d(&"b3MaxInt", [arg0, arg1])

func b3Min(arg0, arg1):
	return raw.call_box3d(&"b3Min", [arg0, arg1])

func b3MinFloat(arg0, arg1):
	return raw.call_box3d(&"b3MinFloat", [arg0, arg1])

func b3MinInt(arg0, arg1):
	return raw.call_box3d(&"b3MinInt", [arg0, arg1])

func b3MotorJoint_GetAngularDampingRatio(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetAngularDampingRatio", [arg0])

func b3MotorJoint_GetAngularHertz(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetAngularHertz", [arg0])

func b3MotorJoint_GetAngularVelocity(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetAngularVelocity", [arg0])

func b3MotorJoint_GetLinearDampingRatio(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetLinearDampingRatio", [arg0])

func b3MotorJoint_GetLinearHertz(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetLinearHertz", [arg0])

func b3MotorJoint_GetLinearVelocity(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetLinearVelocity", [arg0])

func b3MotorJoint_GetMaxSpringForce(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetMaxSpringForce", [arg0])

func b3MotorJoint_GetMaxSpringTorque(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetMaxSpringTorque", [arg0])

func b3MotorJoint_GetMaxVelocityForce(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetMaxVelocityForce", [arg0])

func b3MotorJoint_GetMaxVelocityTorque(arg0):
	return raw.call_box3d(&"b3MotorJoint_GetMaxVelocityTorque", [arg0])

func b3MotorJoint_SetAngularDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetAngularDampingRatio", [arg0, arg1])

func b3MotorJoint_SetAngularHertz(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetAngularHertz", [arg0, arg1])

func b3MotorJoint_SetAngularVelocity(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetAngularVelocity", [arg0, arg1])

func b3MotorJoint_SetLinearDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetLinearDampingRatio", [arg0, arg1])

func b3MotorJoint_SetLinearHertz(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetLinearHertz", [arg0, arg1])

func b3MotorJoint_SetLinearVelocity(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetLinearVelocity", [arg0, arg1])

func b3MotorJoint_SetMaxSpringForce(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetMaxSpringForce", [arg0, arg1])

func b3MotorJoint_SetMaxSpringTorque(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetMaxSpringTorque", [arg0, arg1])

func b3MotorJoint_SetMaxVelocityForce(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetMaxVelocityForce", [arg0, arg1])

func b3MotorJoint_SetMaxVelocityTorque(arg0, arg1):
	return raw.call_box3d(&"b3MotorJoint_SetMaxVelocityTorque", [arg0, arg1])

func b3Mul(arg0, arg1):
	return raw.call_box3d(&"b3Mul", [arg0, arg1])

func b3MulAdd(arg0, arg1, arg2):
	return raw.call_box3d(&"b3MulAdd", [arg0, arg1, arg2])

func b3MulMM(arg0, arg1):
	return raw.call_box3d(&"b3MulMM", [arg0, arg1])

func b3MulMV(arg0, arg1):
	return raw.call_box3d(&"b3MulMV", [arg0, arg1])

func b3MulQuat(arg0, arg1):
	return raw.call_box3d(&"b3MulQuat", [arg0, arg1])

func b3MulSM(arg0, arg1):
	return raw.call_box3d(&"b3MulSM", [arg0, arg1])

func b3MulSV(arg0, arg1):
	return raw.call_box3d(&"b3MulSV", [arg0, arg1])

func b3MulSub(arg0, arg1, arg2):
	return raw.call_box3d(&"b3MulSub", [arg0, arg1, arg2])

func b3MulTransforms(arg0, arg1):
	return raw.call_box3d(&"b3MulTransforms", [arg0, arg1])

func b3MulWorldTransforms(arg0, arg1):
	return raw.call_box3d(&"b3MulWorldTransforms", [arg0, arg1])

func b3NLerp(arg0, arg1, arg2):
	return raw.call_box3d(&"b3NLerp", [arg0, arg1, arg2])

func b3Neg(arg0):
	return raw.call_box3d(&"b3Neg", [arg0])

func b3NegateMat3(arg0):
	return raw.call_box3d(&"b3NegateMat3", [arg0])

func b3NegateQuat(arg0):
	return raw.call_box3d(&"b3NegateQuat", [arg0])

func b3Normalize(arg0):
	return raw.call_box3d(&"b3Normalize", [arg0])

func b3NormalizeQuat(arg0):
	return raw.call_box3d(&"b3NormalizeQuat", [arg0])

func b3OffsetAABB(arg0, arg1):
	return raw.call_box3d(&"b3OffsetAABB", [arg0, arg1])

func b3OffsetPos(arg0, arg1):
	return raw.call_box3d(&"b3OffsetPos", [arg0, arg1])

func b3OverlapCapsule(arg0, arg1, arg2):
	return raw.call_box3d(&"b3OverlapCapsule", [arg0, arg1, arg2])

func b3OverlapCompound(arg0, arg1, arg2):
	return raw.call_box3d(&"b3OverlapCompound", [arg0, arg1, arg2])

func b3OverlapHeightField(arg0, arg1, arg2):
	return raw.call_box3d(&"b3OverlapHeightField", [arg0, arg1, arg2])

func b3OverlapHull(arg0, arg1, arg2):
	return raw.call_box3d(&"b3OverlapHull", [arg0, arg1, arg2])

func b3OverlapMesh(arg0, arg1, arg2):
	return raw.call_box3d(&"b3OverlapMesh", [arg0, arg1, arg2])

func b3OverlapSphere(arg0, arg1, arg2):
	return raw.call_box3d(&"b3OverlapSphere", [arg0, arg1, arg2])

func b3ParallelJoint_GetMaxTorque(arg0):
	return raw.call_box3d(&"b3ParallelJoint_GetMaxTorque", [arg0])

func b3ParallelJoint_GetSpringDampingRatio(arg0):
	return raw.call_box3d(&"b3ParallelJoint_GetSpringDampingRatio", [arg0])

func b3ParallelJoint_GetSpringHertz(arg0):
	return raw.call_box3d(&"b3ParallelJoint_GetSpringHertz", [arg0])

func b3ParallelJoint_SetMaxTorque(arg0, arg1):
	return raw.call_box3d(&"b3ParallelJoint_SetMaxTorque", [arg0, arg1])

func b3ParallelJoint_SetSpringDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3ParallelJoint_SetSpringDampingRatio", [arg0, arg1])

func b3ParallelJoint_SetSpringHertz(arg0, arg1):
	return raw.call_box3d(&"b3ParallelJoint_SetSpringHertz", [arg0, arg1])

func b3Perp(arg0):
	return raw.call_box3d(&"b3Perp", [arg0])

func b3PointToSegmentDistance(arg0, arg1, arg2):
	return raw.call_box3d(&"b3PointToSegmentDistance", [arg0, arg1, arg2])

func b3PrismaticJoint_EnableLimit(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_EnableLimit", [arg0, arg1])

func b3PrismaticJoint_EnableMotor(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_EnableMotor", [arg0, arg1])

func b3PrismaticJoint_EnableSpring(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_EnableSpring", [arg0, arg1])

func b3PrismaticJoint_GetLowerLimit(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetLowerLimit", [arg0])

func b3PrismaticJoint_GetMaxMotorForce(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetMaxMotorForce", [arg0])

func b3PrismaticJoint_GetMotorForce(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetMotorForce", [arg0])

func b3PrismaticJoint_GetMotorSpeed(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetMotorSpeed", [arg0])

func b3PrismaticJoint_GetSpeed(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetSpeed", [arg0])

func b3PrismaticJoint_GetSpringDampingRatio(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetSpringDampingRatio", [arg0])

func b3PrismaticJoint_GetSpringHertz(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetSpringHertz", [arg0])

func b3PrismaticJoint_GetTargetTranslation(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetTargetTranslation", [arg0])

func b3PrismaticJoint_GetTranslation(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetTranslation", [arg0])

func b3PrismaticJoint_GetUpperLimit(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_GetUpperLimit", [arg0])

func b3PrismaticJoint_IsLimitEnabled(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_IsLimitEnabled", [arg0])

func b3PrismaticJoint_IsMotorEnabled(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_IsMotorEnabled", [arg0])

func b3PrismaticJoint_IsSpringEnabled(arg0):
	return raw.call_box3d(&"b3PrismaticJoint_IsSpringEnabled", [arg0])

func b3PrismaticJoint_SetLimits(arg0, arg1, arg2):
	return raw.call_box3d(&"b3PrismaticJoint_SetLimits", [arg0, arg1, arg2])

func b3PrismaticJoint_SetMaxMotorForce(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_SetMaxMotorForce", [arg0, arg1])

func b3PrismaticJoint_SetMotorSpeed(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_SetMotorSpeed", [arg0, arg1])

func b3PrismaticJoint_SetSpringDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_SetSpringDampingRatio", [arg0, arg1])

func b3PrismaticJoint_SetSpringHertz(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_SetSpringHertz", [arg0, arg1])

func b3PrismaticJoint_SetTargetTranslation(arg0, arg1):
	return raw.call_box3d(&"b3PrismaticJoint_SetTargetTranslation", [arg0, arg1])

func b3QueryCompound(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3QueryCompound", [arg0, arg1, arg2, arg3])

func b3QueryHeightField(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3QueryHeightField", [arg0, arg1, arg2, arg3])

func b3QueryMesh(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3QueryMesh", [arg0, arg1, arg2, arg3])

func b3RayCastCapsule(arg0, arg1):
	return raw.call_box3d(&"b3RayCastCapsule", [arg0, arg1])

func b3RayCastCompound(arg0, arg1):
	return raw.call_box3d(&"b3RayCastCompound", [arg0, arg1])

func b3RayCastHeightField(arg0, arg1):
	return raw.call_box3d(&"b3RayCastHeightField", [arg0, arg1])

func b3RayCastHollowSphere(arg0, arg1):
	return raw.call_box3d(&"b3RayCastHollowSphere", [arg0, arg1])

func b3RayCastHull(arg0, arg1):
	return raw.call_box3d(&"b3RayCastHull", [arg0, arg1])

func b3RayCastMesh(arg0, arg1):
	return raw.call_box3d(&"b3RayCastMesh", [arg0, arg1])

func b3RayCastSphere(arg0, arg1):
	return raw.call_box3d(&"b3RayCastSphere", [arg0, arg1])

func b3ReadBinaryFile(arg0, arg1, arg2):
	return raw.call_box3d(&"b3ReadBinaryFile", [arg0, arg1, arg2])

func b3RecPlayer_Create(arg0, arg1, arg2):
	return raw.call_box3d(&"b3RecPlayer_Create", [arg0, arg1, arg2])

func b3RecPlayer_Destroy(arg0):
	return raw.call_box3d(&"b3RecPlayer_Destroy", [arg0])

func b3RecPlayer_DrawFrameQueries(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3RecPlayer_DrawFrameQueries", [arg0, arg1, arg2, arg3])

func b3RecPlayer_GetBodyCount(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetBodyCount", [arg0])

func b3RecPlayer_GetBodyId(arg0, arg1):
	return raw.call_box3d(&"b3RecPlayer_GetBodyId", [arg0, arg1])

func b3RecPlayer_GetDivergeFrame(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetDivergeFrame", [arg0])

func b3RecPlayer_GetFrame(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetFrame", [arg0])

func b3RecPlayer_GetFrameCount(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetFrameCount", [arg0])

func b3RecPlayer_GetFrameQuery(arg0, arg1):
	return raw.call_box3d(&"b3RecPlayer_GetFrameQuery", [arg0, arg1])

func b3RecPlayer_GetFrameQueryCount(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetFrameQueryCount", [arg0])

func b3RecPlayer_GetFrameQueryHit(arg0, arg1, arg2):
	return raw.call_box3d(&"b3RecPlayer_GetFrameQueryHit", [arg0, arg1, arg2])

func b3RecPlayer_GetInfo(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetInfo", [arg0])

func b3RecPlayer_GetKeyframeBudget(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetKeyframeBudget", [arg0])

func b3RecPlayer_GetKeyframeBytes(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetKeyframeBytes", [arg0])

func b3RecPlayer_GetKeyframeInterval(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetKeyframeInterval", [arg0])

func b3RecPlayer_GetKeyframeMinInterval(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetKeyframeMinInterval", [arg0])

func b3RecPlayer_GetWorldId(arg0):
	return raw.call_box3d(&"b3RecPlayer_GetWorldId", [arg0])

func b3RecPlayer_HasDiverged(arg0):
	return raw.call_box3d(&"b3RecPlayer_HasDiverged", [arg0])

func b3RecPlayer_IsAtEnd(arg0):
	return raw.call_box3d(&"b3RecPlayer_IsAtEnd", [arg0])

func b3RecPlayer_IsAtPreStep(arg0):
	return raw.call_box3d(&"b3RecPlayer_IsAtPreStep", [arg0])

func b3RecPlayer_Restart(arg0):
	return raw.call_box3d(&"b3RecPlayer_Restart", [arg0])

func b3RecPlayer_SeekFrame(arg0, arg1):
	return raw.call_box3d(&"b3RecPlayer_SeekFrame", [arg0, arg1])

func b3RecPlayer_SetDebugShapeCallbacks(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3RecPlayer_SetDebugShapeCallbacks", [arg0, arg1, arg2, arg3])

func b3RecPlayer_SetKeyframePolicy(arg0, arg1, arg2):
	return raw.call_box3d(&"b3RecPlayer_SetKeyframePolicy", [arg0, arg1, arg2])

func b3RecPlayer_SetWorkerCount(arg0, arg1):
	return raw.call_box3d(&"b3RecPlayer_SetWorkerCount", [arg0, arg1])

func b3RecPlayer_StepFrame(arg0):
	return raw.call_box3d(&"b3RecPlayer_StepFrame", [arg0])

func b3RecPlayer_SubStepFrame(arg0):
	return raw.call_box3d(&"b3RecPlayer_SubStepFrame", [arg0])

func b3Recording_GetData(arg0):
	return raw.call_box3d(&"b3Recording_GetData", [arg0])

func b3Recording_GetSize(arg0):
	return raw.call_box3d(&"b3Recording_GetSize", [arg0])

func b3RevoluteJoint_EnableLimit(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_EnableLimit", [arg0, arg1])

func b3RevoluteJoint_EnableMotor(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_EnableMotor", [arg0, arg1])

func b3RevoluteJoint_EnableSpring(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_EnableSpring", [arg0, arg1])

func b3RevoluteJoint_GetAngle(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetAngle", [arg0])

func b3RevoluteJoint_GetLowerLimit(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetLowerLimit", [arg0])

func b3RevoluteJoint_GetMaxMotorTorque(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetMaxMotorTorque", [arg0])

func b3RevoluteJoint_GetMotorSpeed(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetMotorSpeed", [arg0])

func b3RevoluteJoint_GetMotorTorque(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetMotorTorque", [arg0])

func b3RevoluteJoint_GetSpringDampingRatio(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetSpringDampingRatio", [arg0])

func b3RevoluteJoint_GetSpringHertz(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetSpringHertz", [arg0])

func b3RevoluteJoint_GetTargetAngle(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetTargetAngle", [arg0])

func b3RevoluteJoint_GetUpperLimit(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_GetUpperLimit", [arg0])

func b3RevoluteJoint_IsLimitEnabled(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_IsLimitEnabled", [arg0])

func b3RevoluteJoint_IsMotorEnabled(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_IsMotorEnabled", [arg0])

func b3RevoluteJoint_IsSpringEnabled(arg0):
	return raw.call_box3d(&"b3RevoluteJoint_IsSpringEnabled", [arg0])

func b3RevoluteJoint_SetLimits(arg0, arg1, arg2):
	return raw.call_box3d(&"b3RevoluteJoint_SetLimits", [arg0, arg1, arg2])

func b3RevoluteJoint_SetMaxMotorTorque(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_SetMaxMotorTorque", [arg0, arg1])

func b3RevoluteJoint_SetMotorSpeed(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_SetMotorSpeed", [arg0, arg1])

func b3RevoluteJoint_SetSpringDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_SetSpringDampingRatio", [arg0, arg1])

func b3RevoluteJoint_SetSpringHertz(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_SetSpringHertz", [arg0, arg1])

func b3RevoluteJoint_SetTargetAngle(arg0, arg1):
	return raw.call_box3d(&"b3RevoluteJoint_SetTargetAngle", [arg0, arg1])

func b3RotateVector(arg0, arg1):
	return raw.call_box3d(&"b3RotateVector", [arg0, arg1])

func b3RoundDownFloat(arg0):
	return raw.call_box3d(&"b3RoundDownFloat", [arg0])

func b3RoundUpFloat(arg0):
	return raw.call_box3d(&"b3RoundUpFloat", [arg0])

func b3SafeScale(arg0):
	return raw.call_box3d(&"b3SafeScale", [arg0])

func b3SaveRecordingToFile(arg0, arg1):
	return raw.call_box3d(&"b3SaveRecordingToFile", [arg0, arg1])

func b3ScaleBox(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3ScaleBox", [arg0, arg1, arg2, arg3])

func b3SegmentDistance(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3SegmentDistance", [arg0, arg1, arg2, arg3])

func b3SetAllocator(arg0, arg1):
	return raw.call_box3d(&"b3SetAllocator", [arg0, arg1])

func b3SetAssertFcn(arg0):
	return raw.call_box3d(&"b3SetAssertFcn", [arg0])

func b3SetLengthUnitsPerMeter(arg0):
	return raw.call_box3d(&"b3SetLengthUnitsPerMeter", [arg0])

func b3SetLogFcn(arg0):
	return raw.call_box3d(&"b3SetLogFcn", [arg0])

func b3SetStallThreshold(arg0):
	return raw.call_box3d(&"b3SetStallThreshold", [arg0])

func b3ShapeCast(arg0):
	return raw.call_box3d(&"b3ShapeCast", [arg0])

func b3ShapeCastCapsule(arg0, arg1):
	return raw.call_box3d(&"b3ShapeCastCapsule", [arg0, arg1])

func b3ShapeCastCompound(arg0, arg1):
	return raw.call_box3d(&"b3ShapeCastCompound", [arg0, arg1])

func b3ShapeCastHeightField(arg0, arg1):
	return raw.call_box3d(&"b3ShapeCastHeightField", [arg0, arg1])

func b3ShapeCastHull(arg0, arg1):
	return raw.call_box3d(&"b3ShapeCastHull", [arg0, arg1])

func b3ShapeCastMesh(arg0, arg1):
	return raw.call_box3d(&"b3ShapeCastMesh", [arg0, arg1])

func b3ShapeCastSphere(arg0, arg1):
	return raw.call_box3d(&"b3ShapeCastSphere", [arg0, arg1])

func b3ShapeDistance(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3ShapeDistance", [arg0, arg1, arg2, arg3])

func b3Shape_ApplyWind(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3Shape_ApplyWind", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3Shape_AreContactEventsEnabled(arg0):
	return raw.call_box3d(&"b3Shape_AreContactEventsEnabled", [arg0])

func b3Shape_AreHitEventsEnabled(arg0):
	return raw.call_box3d(&"b3Shape_AreHitEventsEnabled", [arg0])

func b3Shape_ArePreSolveEventsEnabled(arg0):
	return raw.call_box3d(&"b3Shape_ArePreSolveEventsEnabled", [arg0])

func b3Shape_AreSensorEventsEnabled(arg0):
	return raw.call_box3d(&"b3Shape_AreSensorEventsEnabled", [arg0])

func b3Shape_ComputeMassData(arg0):
	return raw.call_box3d(&"b3Shape_ComputeMassData", [arg0])

func b3Shape_EnableContactEvents(arg0, arg1):
	return raw.call_box3d(&"b3Shape_EnableContactEvents", [arg0, arg1])

func b3Shape_EnableHitEvents(arg0, arg1):
	return raw.call_box3d(&"b3Shape_EnableHitEvents", [arg0, arg1])

func b3Shape_EnablePreSolveEvents(arg0, arg1):
	return raw.call_box3d(&"b3Shape_EnablePreSolveEvents", [arg0, arg1])

func b3Shape_EnableSensorEvents(arg0, arg1):
	return raw.call_box3d(&"b3Shape_EnableSensorEvents", [arg0, arg1])

func b3Shape_GetAABB(arg0):
	return raw.call_box3d(&"b3Shape_GetAABB", [arg0])

func b3Shape_GetBody(arg0):
	return raw.call_box3d(&"b3Shape_GetBody", [arg0])

func b3Shape_GetCapsule(arg0):
	return raw.call_box3d(&"b3Shape_GetCapsule", [arg0])

func b3Shape_GetClosestPoint(arg0, arg1):
	return raw.call_box3d(&"b3Shape_GetClosestPoint", [arg0, arg1])

func b3Shape_GetContactCapacity(arg0):
	return raw.call_box3d(&"b3Shape_GetContactCapacity", [arg0])

func b3Shape_GetContactData(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_GetContactData", [arg0, arg1, arg2])

func b3Shape_GetDensity(arg0):
	return raw.call_box3d(&"b3Shape_GetDensity", [arg0])

func b3Shape_GetFilter(arg0):
	return raw.call_box3d(&"b3Shape_GetFilter", [arg0])

func b3Shape_GetFriction(arg0):
	return raw.call_box3d(&"b3Shape_GetFriction", [arg0])

func b3Shape_GetHeightField(arg0):
	return raw.call_box3d(&"b3Shape_GetHeightField", [arg0])

func b3Shape_GetHull(arg0):
	return raw.call_box3d(&"b3Shape_GetHull", [arg0])

func b3Shape_GetMesh(arg0):
	return raw.call_box3d(&"b3Shape_GetMesh", [arg0])

func b3Shape_GetMeshMaterialCount(arg0):
	return raw.call_box3d(&"b3Shape_GetMeshMaterialCount", [arg0])

func b3Shape_GetMeshSurfaceMaterial(arg0, arg1):
	return raw.call_box3d(&"b3Shape_GetMeshSurfaceMaterial", [arg0, arg1])

func b3Shape_GetName(arg0):
	return raw.call_box3d(&"b3Shape_GetName", [arg0])

func b3Shape_GetRestitution(arg0):
	return raw.call_box3d(&"b3Shape_GetRestitution", [arg0])

func b3Shape_GetSensorCapacity(arg0):
	return raw.call_box3d(&"b3Shape_GetSensorCapacity", [arg0])

func b3Shape_GetSensorData(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_GetSensorData", [arg0, arg1, arg2])

func b3Shape_GetSphere(arg0):
	return raw.call_box3d(&"b3Shape_GetSphere", [arg0])

func b3Shape_GetSurfaceMaterial(arg0):
	return raw.call_box3d(&"b3Shape_GetSurfaceMaterial", [arg0])

func b3Shape_GetType(arg0):
	return raw.call_box3d(&"b3Shape_GetType", [arg0])

func b3Shape_GetUserData(arg0):
	return raw.call_box3d(&"b3Shape_GetUserData", [arg0])

func b3Shape_GetWorld(arg0):
	return raw.call_box3d(&"b3Shape_GetWorld", [arg0])

func b3Shape_IsSensor(arg0):
	return raw.call_box3d(&"b3Shape_IsSensor", [arg0])

func b3Shape_IsValid(arg0):
	return raw.call_box3d(&"b3Shape_IsValid", [arg0])

func b3Shape_RayCast(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_RayCast", [arg0, arg1, arg2])

func b3Shape_SetCapsule(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetCapsule", [arg0, arg1])

func b3Shape_SetDensity(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_SetDensity", [arg0, arg1, arg2])

func b3Shape_SetFilter(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_SetFilter", [arg0, arg1, arg2])

func b3Shape_SetFriction(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetFriction", [arg0, arg1])

func b3Shape_SetHull(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetHull", [arg0, arg1])

func b3Shape_SetMesh(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_SetMesh", [arg0, arg1, arg2])

func b3Shape_SetMeshMaterial(arg0, arg1, arg2):
	return raw.call_box3d(&"b3Shape_SetMeshMaterial", [arg0, arg1, arg2])

func b3Shape_SetName(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetName", [arg0, arg1])

func b3Shape_SetRestitution(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetRestitution", [arg0, arg1])

func b3Shape_SetSphere(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetSphere", [arg0, arg1])

func b3Shape_SetSurfaceMaterial(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetSurfaceMaterial", [arg0, arg1])

func b3Shape_SetUserData(arg0, arg1):
	return raw.call_box3d(&"b3Shape_SetUserData", [arg0, arg1])

func b3Sign(arg0):
	return raw.call_box3d(&"b3Sign", [arg0])

func b3Sin(arg0):
	return raw.call_box3d(&"b3Sin", [arg0])

func b3Sleep(arg0):
	return raw.call_box3d(&"b3Sleep", [arg0])

func b3Solve3(arg0, arg1):
	return raw.call_box3d(&"b3Solve3", [arg0, arg1])

func b3SolvePlanes(arg0, arg1, arg2):
	return raw.call_box3d(&"b3SolvePlanes", [arg0, arg1, arg2])

func b3SphericalJoint_EnableConeLimit(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_EnableConeLimit", [arg0, arg1])

func b3SphericalJoint_EnableMotor(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_EnableMotor", [arg0, arg1])

func b3SphericalJoint_EnableSpring(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_EnableSpring", [arg0, arg1])

func b3SphericalJoint_EnableTwistLimit(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_EnableTwistLimit", [arg0, arg1])

func b3SphericalJoint_GetConeAngle(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetConeAngle", [arg0])

func b3SphericalJoint_GetConeLimit(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetConeLimit", [arg0])

func b3SphericalJoint_GetLowerTwistLimit(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetLowerTwistLimit", [arg0])

func b3SphericalJoint_GetMaxMotorTorque(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetMaxMotorTorque", [arg0])

func b3SphericalJoint_GetMotorTorque(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetMotorTorque", [arg0])

func b3SphericalJoint_GetMotorVelocity(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetMotorVelocity", [arg0])

func b3SphericalJoint_GetSpringDampingRatio(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetSpringDampingRatio", [arg0])

func b3SphericalJoint_GetSpringHertz(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetSpringHertz", [arg0])

func b3SphericalJoint_GetTargetRotation(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetTargetRotation", [arg0])

func b3SphericalJoint_GetTwistAngle(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetTwistAngle", [arg0])

func b3SphericalJoint_GetUpperTwistLimit(arg0):
	return raw.call_box3d(&"b3SphericalJoint_GetUpperTwistLimit", [arg0])

func b3SphericalJoint_IsConeLimitEnabled(arg0):
	return raw.call_box3d(&"b3SphericalJoint_IsConeLimitEnabled", [arg0])

func b3SphericalJoint_IsMotorEnabled(arg0):
	return raw.call_box3d(&"b3SphericalJoint_IsMotorEnabled", [arg0])

func b3SphericalJoint_IsSpringEnabled(arg0):
	return raw.call_box3d(&"b3SphericalJoint_IsSpringEnabled", [arg0])

func b3SphericalJoint_IsTwistLimitEnabled(arg0):
	return raw.call_box3d(&"b3SphericalJoint_IsTwistLimitEnabled", [arg0])

func b3SphericalJoint_SetConeLimit(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_SetConeLimit", [arg0, arg1])

func b3SphericalJoint_SetMaxMotorTorque(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_SetMaxMotorTorque", [arg0, arg1])

func b3SphericalJoint_SetMotorVelocity(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_SetMotorVelocity", [arg0, arg1])

func b3SphericalJoint_SetSpringDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_SetSpringDampingRatio", [arg0, arg1])

func b3SphericalJoint_SetSpringHertz(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_SetSpringHertz", [arg0, arg1])

func b3SphericalJoint_SetTargetRotation(arg0, arg1):
	return raw.call_box3d(&"b3SphericalJoint_SetTargetRotation", [arg0, arg1])

func b3SphericalJoint_SetTwistLimits(arg0, arg1, arg2):
	return raw.call_box3d(&"b3SphericalJoint_SetTwistLimits", [arg0, arg1, arg2])

func b3Steiner(arg0, arg1):
	return raw.call_box3d(&"b3Steiner", [arg0, arg1])

func b3StoreBodyId(arg0):
	return raw.call_box3d(&"b3StoreBodyId", [arg0])

func b3StoreContactId(arg0, arg1):
	return raw.call_box3d(&"b3StoreContactId", [arg0, arg1])

func b3StoreJointId(arg0):
	return raw.call_box3d(&"b3StoreJointId", [arg0])

func b3StoreShapeId(arg0):
	return raw.call_box3d(&"b3StoreShapeId", [arg0])

func b3StoreWorldId(arg0):
	return raw.call_box3d(&"b3StoreWorldId", [arg0])

func b3Sub(arg0, arg1):
	return raw.call_box3d(&"b3Sub", [arg0, arg1])

func b3SubMM(arg0, arg1):
	return raw.call_box3d(&"b3SubMM", [arg0, arg1])

func b3SubPos(arg0, arg1):
	return raw.call_box3d(&"b3SubPos", [arg0, arg1])

func b3TimeOfImpact(arg0):
	return raw.call_box3d(&"b3TimeOfImpact", [arg0])

func b3ToPos(arg0):
	return raw.call_box3d(&"b3ToPos", [arg0])

func b3ToRelativeTransform(arg0, arg1):
	return raw.call_box3d(&"b3ToRelativeTransform", [arg0, arg1])

func b3ToVec3(arg0):
	return raw.call_box3d(&"b3ToVec3", [arg0])

func b3TransformPoint(arg0, arg1):
	return raw.call_box3d(&"b3TransformPoint", [arg0, arg1])

func b3TransformWorldPoint(arg0, arg1):
	return raw.call_box3d(&"b3TransformWorldPoint", [arg0, arg1])

func b3Transpose(arg0):
	return raw.call_box3d(&"b3Transpose", [arg0])

func b3UnwindAngle(arg0):
	return raw.call_box3d(&"b3UnwindAngle", [arg0])

func b3ValidateReplay(arg0, arg1, arg2):
	return raw.call_box3d(&"b3ValidateReplay", [arg0, arg1, arg2])

func b3WeldJoint_GetAngularDampingRatio(arg0):
	return raw.call_box3d(&"b3WeldJoint_GetAngularDampingRatio", [arg0])

func b3WeldJoint_GetAngularHertz(arg0):
	return raw.call_box3d(&"b3WeldJoint_GetAngularHertz", [arg0])

func b3WeldJoint_GetLinearDampingRatio(arg0):
	return raw.call_box3d(&"b3WeldJoint_GetLinearDampingRatio", [arg0])

func b3WeldJoint_GetLinearHertz(arg0):
	return raw.call_box3d(&"b3WeldJoint_GetLinearHertz", [arg0])

func b3WeldJoint_SetAngularDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3WeldJoint_SetAngularDampingRatio", [arg0, arg1])

func b3WeldJoint_SetAngularHertz(arg0, arg1):
	return raw.call_box3d(&"b3WeldJoint_SetAngularHertz", [arg0, arg1])

func b3WeldJoint_SetLinearDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3WeldJoint_SetLinearDampingRatio", [arg0, arg1])

func b3WeldJoint_SetLinearHertz(arg0, arg1):
	return raw.call_box3d(&"b3WeldJoint_SetLinearHertz", [arg0, arg1])

func b3WheelJoint_EnableSpinMotor(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_EnableSpinMotor", [arg0, arg1])

func b3WheelJoint_EnableSteering(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_EnableSteering", [arg0, arg1])

func b3WheelJoint_EnableSteeringLimit(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_EnableSteeringLimit", [arg0, arg1])

func b3WheelJoint_EnableSuspension(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_EnableSuspension", [arg0, arg1])

func b3WheelJoint_EnableSuspensionLimit(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_EnableSuspensionLimit", [arg0, arg1])

func b3WheelJoint_GetLowerSteeringLimit(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetLowerSteeringLimit", [arg0])

func b3WheelJoint_GetLowerSuspensionLimit(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetLowerSuspensionLimit", [arg0])

func b3WheelJoint_GetMaxSpinTorque(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetMaxSpinTorque", [arg0])

func b3WheelJoint_GetMaxSteeringTorque(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetMaxSteeringTorque", [arg0])

func b3WheelJoint_GetSpinMotorSpeed(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSpinMotorSpeed", [arg0])

func b3WheelJoint_GetSpinSpeed(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSpinSpeed", [arg0])

func b3WheelJoint_GetSpinTorque(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSpinTorque", [arg0])

func b3WheelJoint_GetSteeringAngle(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSteeringAngle", [arg0])

func b3WheelJoint_GetSteeringDampingRatio(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSteeringDampingRatio", [arg0])

func b3WheelJoint_GetSteeringHertz(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSteeringHertz", [arg0])

func b3WheelJoint_GetSteeringTorque(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSteeringTorque", [arg0])

func b3WheelJoint_GetSuspensionDampingRatio(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSuspensionDampingRatio", [arg0])

func b3WheelJoint_GetSuspensionHertz(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetSuspensionHertz", [arg0])

func b3WheelJoint_GetTargetSteeringAngle(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetTargetSteeringAngle", [arg0])

func b3WheelJoint_GetUpperSteeringLimit(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetUpperSteeringLimit", [arg0])

func b3WheelJoint_GetUpperSuspensionLimit(arg0):
	return raw.call_box3d(&"b3WheelJoint_GetUpperSuspensionLimit", [arg0])

func b3WheelJoint_IsSpinMotorEnabled(arg0):
	return raw.call_box3d(&"b3WheelJoint_IsSpinMotorEnabled", [arg0])

func b3WheelJoint_IsSteeringEnabled(arg0):
	return raw.call_box3d(&"b3WheelJoint_IsSteeringEnabled", [arg0])

func b3WheelJoint_IsSteeringLimitEnabled(arg0):
	return raw.call_box3d(&"b3WheelJoint_IsSteeringLimitEnabled", [arg0])

func b3WheelJoint_IsSuspensionEnabled(arg0):
	return raw.call_box3d(&"b3WheelJoint_IsSuspensionEnabled", [arg0])

func b3WheelJoint_IsSuspensionLimitEnabled(arg0):
	return raw.call_box3d(&"b3WheelJoint_IsSuspensionLimitEnabled", [arg0])

func b3WheelJoint_SetMaxSpinTorque(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetMaxSpinTorque", [arg0, arg1])

func b3WheelJoint_SetMaxSteeringTorque(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetMaxSteeringTorque", [arg0, arg1])

func b3WheelJoint_SetSpinMotorSpeed(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetSpinMotorSpeed", [arg0, arg1])

func b3WheelJoint_SetSteeringDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetSteeringDampingRatio", [arg0, arg1])

func b3WheelJoint_SetSteeringHertz(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetSteeringHertz", [arg0, arg1])

func b3WheelJoint_SetSteeringLimits(arg0, arg1, arg2):
	return raw.call_box3d(&"b3WheelJoint_SetSteeringLimits", [arg0, arg1, arg2])

func b3WheelJoint_SetSuspensionDampingRatio(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetSuspensionDampingRatio", [arg0, arg1])

func b3WheelJoint_SetSuspensionHertz(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetSuspensionHertz", [arg0, arg1])

func b3WheelJoint_SetSuspensionLimits(arg0, arg1, arg2):
	return raw.call_box3d(&"b3WheelJoint_SetSuspensionLimits", [arg0, arg1, arg2])

func b3WheelJoint_SetTargetSteeringAngle(arg0, arg1):
	return raw.call_box3d(&"b3WheelJoint_SetTargetSteeringAngle", [arg0, arg1])

func b3World_CastMover(arg0, arg1, arg2, arg3, arg4, arg5, arg6):
	return raw.call_box3d(&"b3World_CastMover", [arg0, arg1, arg2, arg3, arg4, arg5, arg6])

func b3World_CastRay(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3World_CastRay", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3World_CastRayClosest(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3World_CastRayClosest", [arg0, arg1, arg2, arg3])

func b3World_CastShape(arg0, arg1, arg2, arg3, arg4, arg5, arg6):
	return raw.call_box3d(&"b3World_CastShape", [arg0, arg1, arg2, arg3, arg4, arg5, arg6])

func b3World_CollideMover(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3World_CollideMover", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3World_Draw(arg0, arg1, arg2):
	return raw.call_box3d(&"b3World_Draw", [arg0, arg1, arg2])

func b3World_Dump(arg0):
	return raw.call_box3d(&"b3World_Dump", [arg0])

func b3World_DumpAwake(arg0):
	return raw.call_box3d(&"b3World_DumpAwake", [arg0])

func b3World_DumpMemoryStats(arg0):
	return raw.call_box3d(&"b3World_DumpMemoryStats", [arg0])

func b3World_DumpShapeBounds(arg0, arg1):
	return raw.call_box3d(&"b3World_DumpShapeBounds", [arg0, arg1])

func b3World_EnableContinuous(arg0, arg1):
	return raw.call_box3d(&"b3World_EnableContinuous", [arg0, arg1])

func b3World_EnableSleeping(arg0, arg1):
	return raw.call_box3d(&"b3World_EnableSleeping", [arg0, arg1])

func b3World_EnableSpeculative(arg0, arg1):
	return raw.call_box3d(&"b3World_EnableSpeculative", [arg0, arg1])

func b3World_EnableWarmStarting(arg0, arg1):
	return raw.call_box3d(&"b3World_EnableWarmStarting", [arg0, arg1])

func b3World_Explode(arg0, arg1):
	return raw.call_box3d(&"b3World_Explode", [arg0, arg1])

func b3World_GetAwakeBodyCount(arg0):
	return raw.call_box3d(&"b3World_GetAwakeBodyCount", [arg0])

func b3World_GetBodyEvents(arg0):
	return raw.call_box3d(&"b3World_GetBodyEvents", [arg0])

func b3World_GetBounds(arg0):
	return raw.call_box3d(&"b3World_GetBounds", [arg0])

func b3World_GetContactEvents(arg0):
	return raw.call_box3d(&"b3World_GetContactEvents", [arg0])

func b3World_GetContactRecycleDistance(arg0):
	return raw.call_box3d(&"b3World_GetContactRecycleDistance", [arg0])

func b3World_GetCounters(arg0):
	return raw.call_box3d(&"b3World_GetCounters", [arg0])

func b3World_GetGravity(arg0):
	return raw.call_box3d(&"b3World_GetGravity", [arg0])

func b3World_GetHitEventThreshold(arg0):
	return raw.call_box3d(&"b3World_GetHitEventThreshold", [arg0])

func b3World_GetJointEvents(arg0):
	return raw.call_box3d(&"b3World_GetJointEvents", [arg0])

func b3World_GetMaxCapacity(arg0):
	return raw.call_box3d(&"b3World_GetMaxCapacity", [arg0])

func b3World_GetMaximumLinearSpeed(arg0):
	return raw.call_box3d(&"b3World_GetMaximumLinearSpeed", [arg0])

func b3World_GetProfile(arg0):
	return raw.call_box3d(&"b3World_GetProfile", [arg0])

func b3World_GetRestitutionThreshold(arg0):
	return raw.call_box3d(&"b3World_GetRestitutionThreshold", [arg0])

func b3World_GetSensorEvents(arg0):
	return raw.call_box3d(&"b3World_GetSensorEvents", [arg0])

func b3World_GetUserData(arg0):
	return raw.call_box3d(&"b3World_GetUserData", [arg0])

func b3World_GetWorkerCount(arg0):
	return raw.call_box3d(&"b3World_GetWorkerCount", [arg0])

func b3World_IsContinuousEnabled(arg0):
	return raw.call_box3d(&"b3World_IsContinuousEnabled", [arg0])

func b3World_IsSleepingEnabled(arg0):
	return raw.call_box3d(&"b3World_IsSleepingEnabled", [arg0])

func b3World_IsValid(arg0):
	return raw.call_box3d(&"b3World_IsValid", [arg0])

func b3World_IsWarmStartingEnabled(arg0):
	return raw.call_box3d(&"b3World_IsWarmStartingEnabled", [arg0])

func b3World_OverlapAABB(arg0, arg1, arg2, arg3, arg4):
	return raw.call_box3d(&"b3World_OverlapAABB", [arg0, arg1, arg2, arg3, arg4])

func b3World_OverlapShape(arg0, arg1, arg2, arg3, arg4, arg5):
	return raw.call_box3d(&"b3World_OverlapShape", [arg0, arg1, arg2, arg3, arg4, arg5])

func b3World_RebuildStaticTree(arg0):
	return raw.call_box3d(&"b3World_RebuildStaticTree", [arg0])

func b3World_SetContactRecycleDistance(arg0, arg1):
	return raw.call_box3d(&"b3World_SetContactRecycleDistance", [arg0, arg1])

func b3World_SetContactTuning(arg0, arg1, arg2, arg3):
	return raw.call_box3d(&"b3World_SetContactTuning", [arg0, arg1, arg2, arg3])

func b3World_SetCustomFilterCallback(arg0, arg1, arg2):
	return raw.call_box3d(&"b3World_SetCustomFilterCallback", [arg0, arg1, arg2])

func b3World_SetFrictionCallback(arg0, arg1):
	return raw.call_box3d(&"b3World_SetFrictionCallback", [arg0, arg1])

func b3World_SetGravity(arg0, arg1):
	return raw.call_box3d(&"b3World_SetGravity", [arg0, arg1])

func b3World_SetHitEventThreshold(arg0, arg1):
	return raw.call_box3d(&"b3World_SetHitEventThreshold", [arg0, arg1])

func b3World_SetMaximumLinearSpeed(arg0, arg1):
	return raw.call_box3d(&"b3World_SetMaximumLinearSpeed", [arg0, arg1])

func b3World_SetPreSolveCallback(arg0, arg1, arg2):
	return raw.call_box3d(&"b3World_SetPreSolveCallback", [arg0, arg1, arg2])

func b3World_SetRestitutionCallback(arg0, arg1):
	return raw.call_box3d(&"b3World_SetRestitutionCallback", [arg0, arg1])

func b3World_SetRestitutionThreshold(arg0, arg1):
	return raw.call_box3d(&"b3World_SetRestitutionThreshold", [arg0, arg1])

func b3World_SetUserData(arg0, arg1):
	return raw.call_box3d(&"b3World_SetUserData", [arg0, arg1])

func b3World_SetWorkerCount(arg0, arg1):
	return raw.call_box3d(&"b3World_SetWorkerCount", [arg0, arg1])

func b3World_StartRecording(arg0, arg1):
	return raw.call_box3d(&"b3World_StartRecording", [arg0, arg1])

func b3World_Step(arg0, arg1, arg2):
	return raw.call_box3d(&"b3World_Step", [arg0, arg1, arg2])

func b3World_StopRecording(arg0):
	return raw.call_box3d(&"b3World_StopRecording", [arg0])

func b3WriteBinaryFile(arg0, arg1, arg2):
	return raw.call_box3d(&"b3WriteBinaryFile", [arg0, arg1, arg2])

func b3Yield():
	return raw.call_box3d(&"b3Yield", [])
